/** Offline tests of authority, room state, profile validation and real-event highlights. */
import assert from 'node:assert/strict';
import type { PadLink } from '../src/net/links';
import type { HostMessage, PadMessage } from '../src/net/protocol';
import { MomentRecorder, momentTime } from '../src/platform/momentRecorder';
import { loadProfile, normalizeProfile, saveProfile, recordGamePlayed, recordWin } from '../src/platform/profile';
import { isPadMessage, padCodeFromHash, padTokenFromHash, padUrlFor } from '../src/net/protocol';

Object.defineProperty(globalThis, 'window', { value: globalThis, configurable: true });
Object.defineProperty(globalThis, 'location', { value: { search: '', hash: '', origin: 'https://example.com', pathname: '/JoyPad/' }, configurable: true });
const storage = new Map<string, string>();
Object.defineProperty(globalThis, 'localStorage', { value: { getItem: (k: string) => storage.get(k), setItem: (k: string, v: string) => storage.set(k, v) }, configurable: true });
const { PadHost } = await import('../src/net/padHost');
const host = new PadHost();
const wire = host as unknown as { conns: Map<string, PadLink>; onMessage: (link: PadLink, msg: PadMessage) => void; dropConn: (id: string) => void };
function pair(id: string, pid = id) {
  const sent: HostMessage[] = [];
  const link: PadLink = { id, kind: 'webrtc', open: true, send: msg => sent.push(msg as HostMessage), onMessage() {}, onClosed() {}, close() {} };
  wire.conns.set(id, link);
  wire.onMessage(link, { t: 'hello', nick: id, ua: 'test', v: 1, pid });
  return { link, sent, send: (msg: PadMessage) => wire.onMessage(link, msg) };
}
const a = pair('Ada'); const b = pair('Bartek');
assert.equal(host.session().adminSlot, 0);
b.send({ t: 'room', action: { kind: 'locked', value: true } });
assert.equal(host.session().room?.locked, false, 'guest cannot lock');
b.send({ t: 'room', action: { kind: 'kick', slot: 0 } });
b.send({ t: 'room', action: { kind: 'transfer', slot: 1 } });
assert.equal(host.session().roster.length, 2);
assert.equal(host.session().adminSlot, 0, 'guest cannot promote themselves');
b.send({ t: 'suggest', game: 'orbit' });
assert.equal(host.session().roster[1].suggestedGame, 'orbit', 'lobby allows votes');
const immutable = host.snapshot();
assert.equal(immutable.pads[1].suggestedGame, 'orbit', 'snapshots cannot mutate under notification diff');
a.send({ t: 'room', action: { kind: 'suggestions', value: false } });
assert.equal(host.session().roster[1].suggestedGame, undefined);
b.send({ t: 'suggest', game: 'tanks' });
assert.equal(host.session().roster[1].suggestedGame, undefined, 'disabled suggestions enforced on host');
a.send({ t: 'room', action: { kind: 'suggestions', value: true } });
b.send({ t: 'suggest', game: 'snake' });
assert.equal(host.session().roster[1].suggestedGame, 'snake', 'beta games can be voted in after release');
// v1.8: anty-spam — kubełek (3) pozwala zmienić zdanie, rapid-fire jest ignorowany.
b.send({ t: 'suggest', game: 'race' });
assert.equal(host.session().roster[1].suggestedGame, 'race', 'change of mind still works within the bucket');
b.send({ t: 'suggest', game: 'tanks' });
b.send({ t: 'suggest', game: 'orbit' });
b.send({ t: 'suggest', game: 'snake' });
assert.equal(host.session().roster[1].suggestedGame, 'race', 'anti-spam stops rapid-fire beyond the bucket');
const rateLimited = b.sent.filter(m => (m as { t?: string }).t === 'rateLimited');
assert.ok(rateLimited.length >= 2, 'pad is informed about the rate limit');
a.send({ t: 'room', action: { kind: 'locked', value: true } });
const rejected = pair('Intruz');
assert.equal(host.session().roster.length, 2);
assert.equal(rejected.sent.at(-1)?.t, 'rejected');
wire.dropConn(b.link.id);
const returned = pair('Bartek2', 'Bartek');
assert.equal(host.session().roster[1].slot, 1, 'known phone reconnects to a locked room');
a.send({ t: 'room', action: { kind: 'transfer', slot: 1 } });
assert.equal(host.session().adminSlot, 1);
a.send({ t: 'room', action: { kind: 'locked', value: false } });
assert.equal(host.session().room?.locked, true, 'old admin loses authority immediately');
returned.send({ t: 'room', action: { kind: 'dimmed', value: true } });
assert.equal(host.session().room?.dimmed, true);
host.setGame('tanks'); host.setScreen('game');
assert.equal(host.session().room?.dimmed, false, 'starting round restores screen');
returned.send({ t: 'room', action: { kind: 'dimmed', value: true } });
assert.equal(host.session().room?.dimmed, false, 'cannot hide active gameplay');
returned.send({ t: 'profile', profile: { avatar: 'alien', theme: 'mint' } });
assert.equal(host.session().roster[1].profile?.avatar, 'alien'); assert.equal(host.session().roster[1].profile?.theme, 'mint'); assert.ok(host.session().roster[1].profile?.id);
returned.send({ t: 'room', action: { kind: 'kick', slot: 0 } });
assert.equal(host.inputs[0].fire, false);
assert.equal(host.session().roster.length, 1);
const kickedReturn = pair('Ada2', 'Ada');
assert.equal(kickedReturn.sent.at(-1)?.t, 'rejected', 'kick revokes locked-room reconnection grace');
wire.dropConn(returned.link.id);
assert.equal(host.session().adminSlot, null);
host.manageRoom({ kind: 'locked', value: false });
const c = pair('Celina');
assert.equal(host.session().adminSlot, 0, 'new crew gets a live admin');
c.send({ t: 'room', action: { kind: '__proto__', value: true } } as unknown as PadMessage);
c.send({ t: 'room', action: { kind: 'locked', value: 'yes' } } as unknown as PadMessage);
assert.equal(host.session().room?.locked, false);
assert.equal(Object.getPrototypeOf(host.session().room!), Object.prototype);
console.log('ROOM SELFTEST: OK (authority, transfer, lock, reconnection, kick, suggestions, dimming, malformed messages)');

const safeProfile = normalizeProfile({ avatar: '__proto__', theme: 'red' });
assert.equal(safeProfile.avatar, 'smile'); assert.equal(safeProfile.theme, 'amber'); assert.ok(safeProfile.id);
saveProfile({ avatar: 'rocket', theme: 'violet', progress: { gamesPlayed: 0, wins: 0, streak: 0, bestStreak: 0, unlocked: [] } });
const saved = loadProfile(); assert.equal(saved.avatar, 'rocket'); assert.equal(saved.theme, 'violet'); assert.ok(saved.id);
const played = recordGamePlayed(saved); const won = recordWin(played, 'snake'); assert.equal(won.progress.gamesPlayed, 1); assert.equal(won.progress.wins, 1); assert.ok(won.progress.unlocked.includes('firstWin')); assert.ok(won.progress.unlocked.includes('snakeBeta'));
storage.set('joypad.profile', 'malformed'); assert.equal(loadProfile().avatar, 'smile');
Object.defineProperty(globalThis, 'localStorage', { configurable: true, get() { throw new Error('private mode'); } });
assert.doesNotThrow(() => saveProfile({ avatar: 'smile', theme: 'amber' }));
assert.equal(loadProfile().theme, 'amber');

// QR exposes only room capability data; no TURN credentials leak into the link.
Object.defineProperty(globalThis, 'location', { value: { search: '?srv=https%3A%2F%2Fsignal.example&turnSecret=secret', hash: '#pad=AB234&key=abcdef123456' , origin: 'https://example.com', pathname: '/JoyPad/' }, configurable: true });
const qr = padUrlFor('ab234', 'abcdef123456'); assert.ok(qr.includes('srv=')); assert.ok(qr.includes('key=abcdef123456')); assert.ok(!qr.includes('turnSecret'));
assert.equal(padCodeFromHash(), 'AB234'); assert.equal(padTokenFromHash(), 'abcdef123456');
assert.equal(isPadMessage({ t: 'input', fwd: 0, turn: 0, fire: false }), true); assert.equal(isPadMessage({ t: 'input', fwd: 'oops' }), false);
console.log('PROTOCOL SELFTEST: OK (QR capability filtering and message guard)');
console.log('PROFILE SELFTEST: OK (allowlist, persistence, corrupt and blocked storage)');

const players = [{ slot: 0, name: 'Ada', color: '#edbd78', score: 0 }, { slot: 1, name: 'Bartek', color: '#bbaaff', score: 0 }];
const rec = new MomentRecorder('tanks');
const tick = (left: number, scoreA = 0, scoreB = 0, paused = false, countdown = 0) => rec.observe({ timeLeft: left, paused, countdown, players: players.map((p, i) => ({ ...p, score: i ? scoreB : scoreA })) });
tick(300, 0, 0, false, 3); tick(300); tick(294, 1); rec.fx(0, 'kill'); tick(290, 2); rec.fx(0, 'kill');
assert.equal(rec.highlights()[0].kind, 'streak'); assert.equal(rec.highlights()[0].at, 10);
tick(290, 2, 0, true); tick(290, 2); tick(278, 2, 3);
assert.ok(rec.highlights().some(m => m.kind === 'lead' && m.slot === 1));
const before = rec.highlights(); rec.fx(1, 'fire'); rec.fx(1, 'hit');
assert.deepEqual(rec.highlights(), before, 'fire and ordinary damage are not fake highlights');
rec.fx(9, 'kill'); assert.deepEqual(rec.highlights(), before, 'unknown slots ignored');
for (let i = 0; i < 200; i++) rec.record({ kind: 'objective', slot: 0, title: 'Test', detail: 'Real engine event', at: i * 20 });
assert.equal((rec as unknown as { events: unknown[] }).events.length, 64);
assert.equal(rec.highlights().length, 3);
assert.equal(new MomentRecorder('tanks').highlights().length, 0, 'new round has no stale highlights');
assert.equal(momentTime(125.9), '02:05');
const race = new MomentRecorder('race');
race.observe({ timeLeft: 200, countdown: 3, paused: false, players });
race.observe({ timeLeft: 170, countdown: 0, paused: false, players: players.map(p => ({ ...p, score: 1 })) });
assert.equal(race.highlights()[0].kind, 'lap');
assert.ok(!race.highlights().some(m => m.kind === 'lead'), 'lap counts cannot invent race overtakes');
console.log('MOMENTS SELFTEST: OK (real FX, streaks, lead changes, timing, bounds, lap semantics, reset)');

// Results can be operated from the pilot without a mouse or a forced rematch.
const { navigateResults } = await import('../src/console/resultsNavigation');
let clicked = -1;
const fakeDocument = { activeElement: null as unknown, querySelectorAll: () => controls };
const controls = [0, 1, 2].map(index => ({ focus() { fakeDocument.activeElement = this; }, click() { clicked = index; } }));
Object.defineProperty(globalThis, 'document', { value: fakeDocument, configurable: true });
assert.equal(navigateResults('select'), false, 'initial select preserves the original rematch shortcut');
assert.equal(navigateResults('down'), true); assert.equal(fakeDocument.activeElement, controls[0]);
assert.equal(navigateResults('select'), true); assert.equal(clicked, 0);
navigateResults('up'); assert.equal(fakeDocument.activeElement, controls[2], 'focus wraps');
assert.equal(navigateResults('home'), false, 'home remains a game-shell action');
console.log('RESULTS NAVIGATION SELFTEST: OK (focus, select, wrap, home and default rematch)');
