import { useEffect, useState } from 'react';

export type Language = 'pl' | 'en';
const KEY = 'joypad.language';
export const LANGUAGES: Record<Language, string> = { pl: 'Polski', en: 'English' };

export function loadLanguage(): Language {
  try { return localStorage.getItem(KEY) === 'en' ? 'en' : 'pl'; } catch { return 'pl'; }
}

export function setLanguage(language: Language) {
  try { localStorage.setItem(KEY, language); } catch { /* optional */ }
  window.dispatchEvent(new CustomEvent('joypad-language', { detail: language }));
}

export function useLanguage() {
  const [language, setState] = useState<Language>(loadLanguage);
  useEffect(() => {
    const update = (event: Event) => setState((event as CustomEvent<Language>).detail || loadLanguage());
    window.addEventListener('joypad-language', update);
    return () => window.removeEventListener('joypad-language', update);
  }, []);
  return language;
}

const messages: Record<Language, Record<string, string>> = {
  pl: {
    'common.close': 'Zamknij', 'common.cancel': 'Anuluj', 'common.confirm': 'Potwierdź', 'common.back': 'Wstecz',
    'common.language': 'Język interfejsu', 'common.languageDetail': 'Polski i English — zmiana obejmuje TV i kontrolery.',
    'common.gallery': 'Galeria Momentów', 'common.save': 'Zapisz do Galerii Momentów', 'common.saved': 'Zapisano w galerii', 'qr.loading': 'Generuję kod…', 'qr.alt': 'Kod QR do podłączenia telefonu',
    'notifications.aria': 'Powiadomienia', 'notifications.close': 'Zamknij powiadomienie', 'notifications.playerJoined': '{name} dołącza do ekipy', 'notifications.playerConnected': 'Pad {n} jest połączony. Miło Cię widzieć!', 'notifications.suggestsGame': '{name} proponuje grę', 'notifications.ready': '{name} jest gotowy', 'notifications.readyDetail': 'Można zaczynać!', 'notifications.playerLeft': '{name} opuszcza pokój', 'notifications.returnDetail': 'Miejsce czeka na ponowne połączenie.', 'notifications.newAdmin': 'Nowy administrator', 'notifications.roomLocked': 'Wejście do pokoju zamknięte', 'notifications.roomOpen': 'Pokój otwarty dla nowych graczy', 'notifications.suggestionsOn': 'Propozycje gier włączone', 'notifications.suggestionsOff': 'Propozycje gier wstrzymane',
    'library.aria': 'Biblioteka JoyPad', 'library.system': 'System konsoli', 'library.roomLocked': 'Pokój zamknięty', 'library.roomReady': 'Pokój gotowy', 'library.roomConnecting': 'Łączenie z pokojem',
    'library.musicOff': 'Wyłącz muzykę menu', 'library.musicOn': 'Włącz muzykę menu', 'library.settings': 'Ustawienia systemu', 'library.room': 'Pokój', 'library.addPlayer': 'Dodaj gracza',
    'library.heading': 'TWOJA BIBLIOTEKA', 'library.launch': 'Uruchom grę', 'library.playAgain': 'Zagraj ponownie', 'library.lastSettings': 'Ostatnie ustawienia · nowa runda',
    'library.session': 'Twoja sesja', 'library.sharedScreen': 'WSPÓLNY EKRAN', 'library.chooseAndPrepare': 'Wybierz grę i uruchom przygotowanie.', 'library.roomCode': 'KOD POKOJU', 'library.openPad': 'Otwórz kontroler',
    'library.admin': 'Administrator', 'library.connected': 'Połączono', 'library.waitingPlayer': 'Czeka na gracza', 'library.crewVotes': 'EKIPA PROPONUJE', 'library.connectionIssue': 'Problem z połączeniem · szczegóły',
    'library.invite': 'W co dziś gramy?', 'library.availableGames': 'Dostępne gry', 'library.upcoming': 'Zapowiedzi', 'library.choose': 'Wybierz', 'library.start': 'Uruchom', 'library.remoteHint': 'Pilot · klawiatura · gamepad',
    'library.whatsNew': 'Co nowego?', 'library.howToStart': 'Jak zacząć?', 'library.version': 'JOYPAD OS · 1.7.0', 'library.musicDisable': 'Wyłącz', 'library.musicEnable': 'Włącz', 'library.libraryMusic': 'muzykę w bibliotece',
    'library.soonTitle': 'Wkrótce w bibliotece', 'library.soonNote': 'Nowe światy pojawią się, gdy będą gotowe — bez odliczania i obietnic dat.', 'library.inDevelopment': 'Zapowiedź',
    'library.helpTitle': 'Usiądź. Połącz. Graj.', 'library.helpScreenTitle': 'Duży ekran', 'library.helpScreen': 'Otwórz JoyPad na komputerze lub telewizorze. Możesz grać na klawiaturze.',
    'library.helpPhoneTitle': 'Twój telefon, Twój kontroler', 'library.helpPhone': 'Zeskanuj kod QR. Pierwszy połączony telefon steruje menu, kolejni gracze dołączają bez konta.',
    'library.helpGameTitle': 'Wybierz swój świat', 'library.helpGame': 'Strzałkami wybierz grę, a Enter ją otwórz. Telefon automatycznie zmienia się w kontroler; gamepad obsługuje bibliotekę.',
    'library.padCheck': 'Sprawdź kontroler · ruch i akcja', 'library.chooseWorld': 'W co dziś gramy?',
    'setup.back': 'JOYPAD / GRY', 'setup.prepare': 'PRZYGOTOWANIE DO GRY', 'setup.nextRound': 'WASZA NASTĘPNA RUNDA', 'setup.settingsCrewStart': 'Ustawienia, skład, start.', 'setup.crew': 'Wasz skład',
    'setup.keyboard': 'Klawiatura', 'setup.freeSlot': 'Wolne miejsce', 'setup.ready': 'GOTOWY ✓', 'setup.connected': 'POŁĄCZONY', 'setup.player': 'GRACZ {n}', 'setup.slot': 'SLOT {n}',
    'setup.nextStep': 'NASTĘPNY KROK', 'setup.invite': 'Zaproś kontrolery', 'setup.start': 'Rozpocznij grę', 'setup.local': 'Graj lokalnie · bez telefonu', 'setup.padCount': '{n} kontrolerów · przejdź do rundy',
    'setup.rules': 'INSTRUKCJA', 'setup.howToPlay': 'Jak grać', 'setup.goal': 'Cel:', 'setup.phone': 'Kontroler:', 'setup.mainOption': 'Główna opcja', 'setup.secondOption': 'Druga opcja', 'setup.keyboardHelp': 'WSAD / strzałki + Q / Enter · P / Esc = pauza',
    'game.statusLoading': 'ŁADOWANIE ARENY…', 'game.matchTournament': 'TURNIEJ {n}/3', 'game.shared': 'WSPÓLNY', 'game.split': 'PODZIELONY EKRAN', 'game.quality': 'DETAL', 'game.actionBonus': 'BONUS NA TRASIE',
    'game.ready': 'PRZYGOTUJ SIĘ', 'game.start': 'START', 'game.loading': 'Ładowanie areny…', 'game.soundOn': 'Włącz dźwięk', 'game.mute': 'Wycisz', 'game.pads': 'Kontrolery i kod pokoju', 'game.pause': 'Pauza (P)', 'game.endRound': 'Zakończ rundę', 'game.back': 'Wróć do JoyPad',
    'results.roundEnd': 'KONIEC RUNDY', 'results.library': 'Biblioteka', 'results.sharedWin': 'WSPÓLNA WYGRANA', 'results.yourMoment': 'TEN MOMENT NALEŻY DO CIEBIE', 'results.newStory': 'KAŻDA RUNDA TO NOWA HISTORIA',
    'results.teamWins': 'DRUŻYNA WYGRYWA', 'results.victory': 'ZWYCIĘSTWO', 'results.summary': 'PODSUMOWANIE', 'results.team': 'Cała drużyna', 'results.goalReached': 'Wspólny cel osiągnięty', 'results.localRecord': 'LOKALNY REKORD',
    'results.lastMove': 'PO OSTATNIM RUCHU', 'results.roundScores': 'Wyniki rundy.', 'results.players': 'GRACZY', 'results.rank': 'GRACZ / KLASYFIKACJA', 'results.stats': 'Wasze liczby · każdy wynik ma znaczenie',
    'results.proposals': 'Ekipa proponuje', 'results.choose': 'Wybierz: {title}', 'results.approval': 'Zatwierdzenie otwiera przygotowanie, nie uruchamia rundy.', 'results.wantsRematch': '{ready}/{total} chce rewanżu', 'results.rematchPrompt': 'Zgłoście się na telefonach',
    'results.rematch': 'Rewanż', 'results.sameSettings': 'Te same ustawienia. Nowa szansa.', 'results.changeGame': 'Zmień grę', 'results.backLibrary': 'Wróć do biblioteki', 'results.changeSettings': 'Zmień ustawienia', 'results.battleMenu': 'Menu bitwy', 'results.nextWorld': 'Wybierz kolejny świat',
    'moments.aria': 'Momenty — najlepsze akcje rundy', 'moments.highlights': 'MOMENTY / NAJLEPSZE AKCJE', 'moments.videoHighlights': 'POWTÓRKI WIDEO',
    'moments.description': 'Najlepsze akcje z rundy. Obejrzyj je teraz lub zapisz wybrane klipy lokalnie w Galerii Momentów.', 'moments.watch': 'OBEJRZYJ', 'moments.eventDetails': 'SZCZEGÓŁY AKCJI · BEZ WIDEO',
    'moments.saved': 'ZAPISANO W GALERII', 'moments.saving': 'ZAPISYWANIE…', 'moments.saveGallery': 'ZAPISZ DO GALERII MOMENTS', 'moments.empty': 'W tej rundzie nie zarejestrowano wyróżniającej się akcji. Następna runda to nowa historia.',
    'moments.roundTime': 'czas rundy', 'moments.noVideo': 'Brak wideo dla potwierdzonego zdarzenia w grze.', 'moments.clipInfo': 'Klip obejmuje krótką chwilę przed akcją i po niej.',
    'moments.saveError': 'Nie udało się zapisać klipu. Pamięć przeglądarki może być niedostępna.',
    'gallery.local': 'Twoja lokalna kolekcja', 'gallery.localInfo': 'Klipy są przechowywane wyłącznie na tym urządzeniu. Nic nie jest wysyłane do internetu.',
    'gallery.empty': 'Galeria jest pusta. Po rundzie zapisz najlepszą akcję, aby wrócić do niej później.', 'gallery.unavailable': 'Galeria nie jest dostępna w tej przeglądarce.', 'gallery.play': 'Odtwórz', 'gallery.download': 'Pobierz', 'gallery.share': 'Udostępnij', 'gallery.delete': 'Usuń', 'gallery.deleteConfirm': 'Usunąć ten klip z tego urządzenia?',
    'gallery.filter': 'Filtr gier', 'gallery.allGames': 'Wszystkie gry', 'gallery.sort': 'Kolejność', 'gallery.newest': 'Najnowsze', 'gallery.oldest': 'Najstarsze', 'gallery.storage': 'Zajęte miejsce', 'gallery.items': 'klipów', 'gallery.close': 'Zamknij', 'gallery.shareUnavailable': 'Udostępnianie nie jest obsługiwane. Możesz pobrać klip.',
    'settings.system': 'TWÓJ SYSTEM', 'settings.intro': 'Małe detale.<br />Twoje doświadczenie.', 'settings.sound': 'Brzmienie systemu', 'settings.soundDetail': 'Subtelny dźwięk. Wyraźna odpowiedź.', 'settings.soundAria': 'Dźwięki systemu',
    'settings.soundOn': 'Dźwięk włączony', 'settings.silence': 'Cisza', 'settings.bigScreenOnly': 'Tylko na dużym ekranie', 'settings.motion': 'Ruch i przejścia', 'settings.motionDetail': 'Spokojne tempo, bez utraty responsywności.', 'settings.motionAria': 'Ruch interfejsu', 'settings.motionSystem': 'Systemowy', 'settings.motionDevice': 'Zgodnie z urządzeniem', 'settings.motionReduced': 'Ograniczony', 'settings.noTransitions': 'Bez animacji przejść',
    'settings.previews': 'Podglądy gier', 'settings.previewDetail': 'Nagrania Full HD, bez dźwięku i bez uruchamiania gry w tle.', 'settings.previewAuto': 'Automatycznie na dużym ekranie', 'settings.previewManual': 'Tylko po naciśnięciu odtwarzania', 'settings.previewRules': 'Telefon, oszczędzanie danych i ograniczony ruch: start ręczny.',
    'settings.moments': 'Momenty · powtórki wideo', 'settings.momentsDetail': 'Obraz gry do 720p / 24 FPS. Bez dźwięku, kamery i mikrofonu. Nagrania nie opuszczają tego urządzenia.', 'settings.recordOn': 'Zapisuj najlepsze akcje', 'settings.recordOff': 'Nagrywanie wyłączone', 'settings.recordRules': 'Od następnej rundy · wyłącz na słabszym sprzęcie. Klipy znikają po wyjściu z gry; możesz je pobrać.',
    'settings.controllerProfile': 'PROFIL KONTROLERA', 'settings.feel': 'Poczuj reakcję', 'settings.hapticsDetail': 'Długość i rytm impulsów, nie siła silnika.', 'settings.haptics': 'Haptyka', 'settings.hapticsOff': 'Wyłączona', 'settings.subtle': 'Subtelna', 'settings.full': 'Wyraźna',
    'settings.hand': 'Dopasowany do dłoni', 'settings.handDetail': 'Strona akcji w grach arcade. Czołgi mają osobny układ.', 'settings.actionButton': 'Przycisk akcji', 'settings.left': 'Po lewej', 'settings.right': 'Po prawej',
    'settings.controlSize': 'Rozmiar sterowania', 'settings.height': 'Wysokość kciuków', 'settings.compact': 'Kompaktowy', 'settings.large': 'Duży', 'settings.lower': 'Niżej', 'settings.higher': 'Wyżej', 'settings.saveAuto': 'Zapisywane automatycznie na tym urządzeniu', 'settings.saveLocal': 'Jeśli przeglądarka zezwala na lokalny zapis',
    'settings.phoneFeatures': 'FUNKCJE TELEFONU', 'settings.preventSleep': 'Nie wygaszaj ekranu', 'settings.fullscreenLandscape': 'Pełny ekran i poziomo', 'settings.tilt': 'Sterowanie przechyłem', 'settings.optionalMode': 'Tryb opcjonalny:', 'settings.privacy': 'Kamera, mikrofon, lokalizacja i powiadomienia nie są potrzebne do kontrolera.',
    'room.screen': 'DUŻY EKRAN', 'room.fullscreen': 'Pełny ekran', 'room.fullscreenOn': 'Obraz wypełnia telewizor', 'room.fullscreenOff': 'Okno przeglądarki', 'room.sectionSwitches': 'POKÓJ', 'room.intro': 'Twoja ekipa. Twoje zasady. Zmiany są wspólne dla TV i wszystkich telefonów.', 'room.lock': 'Zamknij wejście', 'room.locked': 'Nowe telefony nie mogą dołączyć', 'room.open': 'Zaproszenia są aktywne', 'room.voice': 'Głos ekipy', 'room.voteInfo': 'Proponowanie gier w bibliotece i po rundzie',
    'room.dim': 'Przerwa na dużym ekranie', 'room.dimGame': 'Dostępna poza trwającą rundą', 'room.dimInfo': 'Zasłoń bibliotekę, zachowaj połączenia', 'room.crew': 'EKIPA / {count} Z 4', 'room.admin': 'Administrator', 'room.pad': 'Kontroler {n}',
    'room.noPlayers': 'Na razie tylko duży ekran. Zaproś pierwszy telefon.', 'room.transferAria': 'Przekaż administrację: {name}', 'room.disconnectAria': 'Odłącz: {name}', 'room.kickTitle': 'Odłączyć {name}?', 'room.transferTitle': 'Przekazać sterowanie: {name}?',
    'room.kickInfo': 'Ten telefon straci połączenie. Aby zablokować ponowne wejście, zamknij pokój.', 'room.transferInfo': 'Ten gracz będzie sterował menu i pokojem. Duży ekran zawsze zachowuje kontrolę.', 'room.confirm': 'Potwierdź', 'room.cancel': 'Anuluj',
    'pad.room': 'POKÓJ', 'pad.reminder': 'Ekipa czeka. Potwierdź gotowość, gdy będziesz gotowy.', 'pad.paused': 'PAUZA · ODPOCZNIJ', 'pad.ready': 'GOTOWOŚĆ · {count}',
    'snake.direction': 'Steruj kierunkiem.', 'snake.starting': 'Za chwilę start.', 'snake.instruction': 'Dotknij strzałki, aby zmienić kierunek. Nie zawracaj w siebie.', 'snake.dpad': 'Sterowanie kierunkiem węża', 'snake.sprint': 'SPRINT', 'snake.hold': 'PRZYTRZYMAJ', 'snake.settingsInfo': 'Wężowy Wir używa czterech przycisków kierunkowych. Dotknięcie wystarcza — nie musisz prowadzić gałki.', 'snake.beta': 'BETA', 'snake.newGame': 'NOWA GRA', 'snake.points': '{score} pkt', 'snake.backToLibrary': 'Wrócić do biblioteki?', 'snake.pause': 'Pauza', 'snake.settings': 'Ustawienia kontrolera', 'snake.fullscreen': 'Pełny ekran', 'snake.disconnect': 'Odłącz telefon', 'snake.paused': 'PAUZA',
    'joylab.title': 'LAB KONTROLERA', 'joylab.playroom': 'POKÓJ ZABAW', 'joylab.skip': 'WRÓĆ / POMIŃ →', 'joylab.intro': 'Poznaj reakcje kontrolera. Dotyk działa zawsze; czujniki i wibracje zależą od urządzenia. Możesz pominąć test w każdej chwili.', 'joylab.enableSensors': 'WŁĄCZ SENSORY (akcelerometr + żyroskop)', 'joylab.shake': 'POTRZĄŚNIJ = GRZECHOTKA', 'joylab.tilt': 'PRZECHYL = GRAWITACJA', 'joylab.touchZones': 'DOTKNIJ STREF', 'joylab.simulateShake': 'SYMULUJ WSTRZĄS', 'joylab.zonesInfo': 'KAŻDA STREFA MA INNĄ WIBRACJĘ · SPRÓBUJ WSZYSTKICH 8', 'joylab.meter.gravityX': 'GRAW-X', 'joylab.meter.gravityY': 'GRAW-Y', 'joylab.meter.shake': 'WSTRZĄS', 'joylab.meter.gyro': 'ŻYRO', 'joylab.zone.click': 'KLIK', 'joylab.zone.double': 'DUBLET', 'joylab.zone.buzz': 'BUZZ', 'joylab.zone.heart': 'SERCE', 'joylab.zone.flutter': 'TRZEPOT', 'joylab.zone.burst': 'SERIA', 'joylab.zone.wave': 'FALA', 'joylab.zone.drum': 'BĘBEN',
    'pad.quick.title': 'Sprawdź kontroler', 'pad.quick.instruction': 'Porusz gałką i naciśnij akcję. Odpowiedź zobaczysz na TV.', 'pad.quick.skip': 'Gotowe / pomiń', 'pad.quick.explore': 'Sensory i haptyka', 'pad.quick.moveCaption': 'PORUSZ GAŁKĄ', 'pad.quick.action': 'AKCJA', 'pad.quick.actionAria': 'Test akcji', 'pad.quick.dialog': 'Lab kontrolera', 'pad.quick.headline': 'Jeden ruch. I wszystko jasne.', 'pad.quick.tvInstruction': 'Porusz gałką na telefonie, potem naciśnij akcję. Test nie wymaga sensorów ani wibracji.', 'pad.quick.noPhones': 'Połącz telefon, aby rozpocząć test. Możesz też wrócić i grać na klawiaturze.', 'pad.quick.move': 'Ruch', 'pad.quick.moveVerified': 'sprawdzony', 'pad.quick.movePrompt': '— porusz gałką', 'pad.quick.actionVerified': 'sprawdzona', 'pad.quick.actionPrompt': '— naciśnij przycisk', 'pad.quick.exploreSensors': 'Poznaj sensory i haptykę', 'pad.quick.optional': 'Test jest opcjonalny. Wróć do biblioteki, kiedy chcesz.', 'pad.quick.backLibrary': 'Do biblioteki', 'pad.quick.testedAction': 'AKCJA',
    'controller.title': 'Twój kontroler.', 'controller.disconnect': 'Odłącz telefon', 'controller.backLibrary': 'Wrócić do biblioteki?', 'controller.pauseResume': 'PAUZA / WZNÓW', 'controller.allGames': 'WSZYSTKIE GRY', 'controller.confirmExit': 'Zakończyć rundę?', 'controller.nickTitle': 'TWÓJ NICK', 'controller.nickDetail': 'Widoczny w lobby i w każdej grze', 'controller.editNick': 'EDYTUJ', 'controller.nickname': 'Nick gracza', 'controller.saveNick': 'ZAPISZ',
    'controller.exitInfo': 'Wszyscy wrócą do biblioteki. Połączenia telefonów pozostaną aktywne.', 'controller.yesLibrary': 'Tak, wróć do biblioteki', 'controller.stay': 'Zostań w grze',
    'pad.connect': 'POŁĄCZ', 'pad.connecting': 'ŁĄCZENIE…', 'pad.phoneController': 'TELEFON JAKO KONTROLER', 'pad.sharedScreen': 'Wspólny ekran. Twój telefon. Jeden system gry.', 'pad.roomCode': 'KOD Z EKRANU KOMPUTERA', 'pad.yourNick': 'TWÓJ NICK', 'pad.joined': 'DOŁĄCZONO DO POKOJU', 'pad.youArePlayer': 'JESTEŚ GRACZEM',
    'pad.connectAgain': 'Łączymy ponownie. Sterowanie jest bezpiecznie zatrzymane.', 'pad.connectingPad': 'Łączymy Twój kontroler…', 'pad.rotate': 'Obróć telefon poziomo i dotknij, by przejść na pełny ekran',
    'pad.levels': 'POZIOM GŁOŚNOŚCI', 'pad.rumble': 'WSTRZĄS', 'pad.gyro': 'ŻYROSKOP', 'pad.playroom': 'POKÓJ ZABAW', 'pad.skip': 'WRÓĆ / POMIŃ →', 'pad.sensorIntro': 'Poznaj reakcje kontrolera. Dotyk działa zawsze; czujniki i wibracje zależą od urządzenia. Możesz pominąć test w każdej chwili.',
    'pad.enableSensors': 'WŁĄCZ SENSORY (akcelerometr + żyroskop)', 'pad.shake': 'POTRZĄŚNIJ = GRZECHOTKA', 'pad.simulateShake': 'SYMULUJ WSTRZĄS', 'pad.allZones': 'KAŻDA STREFA MA INNĄ WIBRACJĘ · SPRÓBUJ WSZYSTKICH 8',
    'pad.nicknameExample': 'np. Alex', 'pad.connectionDetails': 'Szczegóły połączenia', 'pad.elapsed': 'Czas:', 'pad.server': 'Serwer:', 'pad.stop': 'PRZERWIJ', 'pad.details': 'Szczegóły:',
    'pad.instructions.open': 'Otwórz JoyPad na komputerze lub TV.', 'pad.instructions.scan': 'Zeskanuj kod QR z ekranu albo wpisz tutaj 5‑znakowy kod.', 'pad.instructions.admin': 'Pierwszy telefon zostanie administratorem i wybierze grę. Pozostałe dostaną własne kontrolery.', 'pad.instructions.connection': 'Połączenie przechodzi przez internet, a potem bezpośrednio między urządzeniami. Gdy bezpośrednia ścieżka nie działa (np. telefon korzysta z LTE), gra automatycznie użyje awaryjnego przekaźnika — różne sieci Wi‑Fi i LTE też działają.', 'pad.openHere': '← Otwórz JoyPad na tym urządzeniu',
    'pad.controlSettings': 'Ustawienia sterowania', 'pad.fullscreen': 'Pełny ekran', 'pad.pauseTitle': 'Pauza', 'pad.returnTitle': 'Wróć do JoyPad', 'pad.disconnectTitle': 'Odłącz telefon', 'pad.pauseOverlay': 'PAUZA', 'pad.respawn': 'ODRODZENIE ZA {seconds}s', 'pad.destroyed': 'ZNISZCZONY', 'pad.noTankLead': 'Bitwa już trwa, ale Twój slot', 'pad.noTankTail': 'nie bierze w niej udziału. Dołączysz automatycznie w następnej rundzie.',
    'pad.steering': 'Sterowanie', 'pad.move': 'RUCH', 'pad.front': 'PRZÓD', 'pad.rear': 'TYŁ', 'pad.driveDirection': 'JAZDA • TAM, GDZIE PCHASZ', 'pad.driveForward': 'JAZDA • GÓRA = PRZÓD', 'pad.directionMode': 'KIERUNEK', 'pad.tankMode': 'CZOŁG', 'pad.turret': 'WIEŻA', 'pad.aimAutoFire': 'CELOWANIE • DO KOŃCA = OGIEŃ', 'pad.aimTurret': 'CELOWANIE WIEŻĄ', 'pad.fire': 'OGIEŃ', 'pad.holdBurst': 'PRZYTRZYMAJ = SERIA',
    'pad.layoutTitle': 'UKŁAD KONTROLERA', 'pad.layoutMinimal': 'PROSTY', 'pad.layoutMinimalDesc': '1 gałka + 1 akcja', 'pad.layoutTwin': 'DWA JOYSTICKI', 'pad.layoutTwinDesc': 'jazda + niezależne celowanie', 'pad.drive': 'JAZDA', 'pad.directionDesc': 'Jedź tam, gdzie pchasz gałkę', 'pad.tankDesc': 'Góra = przód, boki = obrót', 'pad.autoFire': 'Autoogień przy celowaniu', 'pad.autoFireDesc': 'W trybie dwóch joysticków wychyl gałkę do końca (czerwony pierścień), aby czołg strzelał sam.', 'pad.swapSides': 'Zamień strony', 'pad.swapDesc': 'Jazda po prawej, celowanie i ogień po lewej (dla leworęcznych).', 'pad.noTankHeading': 'Dołączysz w następnej rundzie',
    'device.wake.off': 'wyłączony', 'device.wake.waiting': 'sprawdzam…', 'device.wake.ready': 'aktywny', 'device.wake.unsupported': 'brak wsparcia', 'device.wake.blocked': 'odrzucony przez system',
    'device.tilt.off': 'wyłączony', 'device.tilt.requesting': 'czekam na zgodę…', 'device.tilt.ready': 'aktywny', 'device.tilt.unsupported': 'brak czujnika/API', 'device.tilt.denied': 'zgoda odrzucona', 'device.fullscreen.active': 'aktywny', 'device.fullscreen.unsupported': 'brak wsparcia', 'device.fullscreen.blocked': 'dotknij przycisku ponownie', 'device.fullscreen.off': 'włączane dopiero po tapnięciu', 'device.test': 'TEST',
    'haptics.status.ready': 'Wibracje gotowe', 'haptics.status.readyDetail': 'API przyjęło test; tryb cichy, DND lub ustawienia systemu mogą nadal wyciszyć impuls.', 'haptics.status.tap': 'Dotknij, aby odblokować', 'haptics.status.tapDetail': 'Przeglądarka nie pokazuje okna zgody. Pierwsze tapnięcie odblokowuje API.', 'haptics.status.unsupported': 'Brak wibracji', 'haptics.status.unsupportedDetail': 'Ta przeglądarka lub urządzenie nie obsługuje Vibration API (np. iOS Safari).', 'haptics.status.blocked': 'Wibracje zablokowane', 'haptics.status.blockedDetail': 'System, tryb cichy albo brak aktywacji blokuje impuls. Spróbuj TEST ponownie po tapnięciu.', 'haptics.status.off': 'Wibracje wyłączone', 'haptics.status.offDetail': 'Wybierz subtelne lub wyraźne w ustawieniach, aby przetestować.',
    'remote.adminNav': 'PILOT ADMINISTRATORA', 'remote.up': 'W górę', 'remote.left': 'W lewo', 'remote.select': 'Wybierz', 'remote.right': 'W prawo', 'remote.down': 'W dół', 'remote.back': 'WSTECZ', 'remote.games': 'GRY', 'remote.onlyAdmin': 'Tylko administrator steruje menu.', 'remote.arrowsHelp': 'Joystick: nawigacja · OK: zatwierdź · X: pełny ekran · Y: kod QR', 'remote.x': 'Pełny ekran', 'remote.y': 'Kod QR', 'remote.controllerMode': 'TRYB KONTROLERA', 'remote.profile': 'Mój profil', 'remote.room': 'Pokój', 'remote.phoneSettings': 'Ustawienia telefonu', 'remote.lobby': 'BIBLIOTEKA', 'remote.results': 'WYNIKI', 'remote.prep': 'PRZYGOTOWANIE', 'remote.roundHint': 'Strzałki: Momenty i akcje. A: wybierz.', 'remote.selectHint': 'Strzałki wybierają. A zatwierdza.', 'remote.rotateHint': 'Obróć pionowo, aby użyć pilota', 'remote.playerPass': 'Twój pad. Twój styl.', 'remote.crewStarting': 'Ekipa zaraz startuje.', 'remote.customizePass': 'Personalizuj Player Pass', 'remote.rematchIntent': 'Chcę rewanż', 'remote.readyIntent': 'Jestem gotowy', 'remote.readyIntentDone': 'Gotowy ✓', 'remote.rematchIntentDone': 'Chcę rewanż ✓', 'remote.rematchCount': 'chętnych na rewanż', 'remote.readyCount': 'gotowych', 'remote.hostStarts': 'Startuje gospodarz', 'remote.remind': 'Przypomnij ekipie', 'remote.reminded': 'Przypomnienie wysłane', 'remote.win': 'Wygrana!', 'remote.roundOver': 'Koniec rundy', 'remote.adminOver': 'Wybierz rewanż albo wróć do biblioteki.', 'remote.guestOver': 'Administrator decyduje o kolejnej rundzie.', 'remote.adminSettings': 'Steruj ustawieniami i rozpocznij rundę przyciskiem OK.', 'remote.guestSettings': 'Administrator ustawia grę. Poczekaj na start.', 'remote.action.rematch': 'REWANŻ', 'remote.action.battle': 'DO BOJU', 'remote.action.mode': 'WYBIERZ TRYB', 'remote.action.start': 'ROZPOCZNIJ', 'remote.adminRole': 'ADMINISTRATOR', 'remote.playerRole': 'GRACZ {n}', 'remote.vertical': 'TRYB PILOTA / PIONOWO', 'remote.loungeMode': 'STREFA GRACZA', 'remote.selectedGame': 'WYBRANA GRA', 'remote.gameMenu': 'MENU GRY', 'remote.navigateAsAdmin': 'Pilotem wybierz grę strzałkami, a następnie naciśnij OK.', 'remote.waitForAdmin': 'Poczekaj, aż administrator wybierze grę.', 'remote.navShoulder': 'L / NAWIGACJA', 'remote.actionShoulder': 'R / AKCJA', 'remote.footerAdmin': 'STERUJ DUŻYM EKRANEM', 'remote.footerGuest': 'POŁĄCZONO Z EKIPĄ',
    'arcadePad.nextRound': 'Runda trwa. Dołączysz od następnej rozgrywki.', 'arcadePad.move': 'RUCH', 'arcadePad.snakeCaption': 'SKRĘCAJ · UNIKAJ ŚCIAN', 'arcadePad.raceCaption': 'KIERUNEK JAZDY', 'arcadePad.orbitCaption': 'LOT · PEŁNIE = DOPALACZ', 'arcadePad.characterCaption': 'PORUSZANIE POSTACIĄ', 'arcadePad.fire': 'OGIEŃ', 'arcadePad.action': 'AKCJA', 'arcadePad.turbo': 'TURBO', 'arcadePad.sprint': 'SPRINT', 'arcadePad.raceHint': 'BONUS / TURBO', 'arcadePad.hold': 'PRZYTRZYMAJ', 'arcadePad.adminMenu': 'Jako administrator możesz zatrzymać grę lub wrócić do biblioteki.', 'arcadePad.guestMenu': 'Administrator zarządza rundą. Możesz rozłączyć ten telefon.', 'arcadePad.pause': 'PAUZA / WZNÓW', 'arcadePad.endRound': 'Zakończyć rundę?', 'arcadePad.exitInfo': 'Wszyscy wrócą do biblioteki. Połączenia telefonów pozostaną aktywne.', 'arcadePad.yesLibrary': 'Tak, wróć do biblioteki', 'arcadePad.stay': 'Zostań w grze', 'arcadePad.menu': 'Menu', 'arcadePad.settings': 'Ustawienia', 'arcadePad.fullscreen': 'Pełny ekran', 'arcadePad.roundHint': 'Dołączysz w następnej rundzie',
    'connection.progress.signal': 'Łączę z serwerem sygnalizacji…', 'connection.progress.signalServer': 'Łączę z serwerem sygnalizacji{server}…', 'connection.progress.signalAttempt': 'Próba {current}/{total} — łączę z serwerem sygnalizacji{server}…', 'connection.progress.findComputer': 'Szukam komputera o tym kodzie…', 'connection.progress.handshake': 'Witam się z komputerem…', 'connection.progress.relay': 'Łączę przez awaryjny przekaźnik (Internet)…', 'connection.progress.reconnect': 'Łączę ponownie…', 'connection.progress.retry': '{reason} Ponawiam za {seconds} s (próba {current}/{total})…',
    'connection.error.webrtcStart': 'Nie udało się uruchomić WebRTC. Sprawdź obsługę połączeń w przeglądarce i ponów próbę.', 'connection.error.linkTimeout': 'Komputer nie odpowiedział podczas negocjowania połączenia P2P.', 'connection.error.signalTimeout': 'Serwer sygnalizacji nie odpowiedział podczas rejestracji telefonu.', 'connection.error.handshake': 'Komputer nie przydzielił miejsca dla tego telefonu.', 'connection.error.hostClosed': 'Komputer zamknął połączenie.', 'connection.error.peerNotReady': 'Komputer nie jest jeszcze widoczny na serwerze.', 'connection.error.peerUnavailable': 'Nie znaleziono pokoju o tym kodzie — ani bezpośrednio, ani przez awaryjny przekaźnik. Kod może się zmienić po odświeżeniu strony komputera. Zeskanuj kod QR ponownie albo przepisz kod z ekranu.', 'connection.error.fallback': 'Nie udało się połączyć ani bezpośrednio (WebRTC), ani przez awaryjny przekaźnik internetowy.', 'connection.error.browserUnsupported': 'Ta przeglądarka nie obsługuje WebRTC. Łączenie bezpośrednie jest niedostępne; sprawdzono też awaryjny przekaźnik.', 'connection.error.signalingRejected': 'Serwer sygnalizacji odrzucił połączenie ({type}).', 'connection.error.signalSsl': 'Serwer sygnalizacji nie obsługuje szyfrowanego połączenia.', 'connection.error.signalOffline': 'Brak łączności z serwerem sygnalizacji.', 'connection.error.signalInterrupted': 'Chwilowy brak łączności z serwerem sygnalizacji (gra działa dalej).', 'connection.error.generic': 'Błąd połączenia: {type}.', 'connection.error.lost': 'Utracono połączenie z komputerem — próbuję połączyć ponownie…', 'connection.error.summary': 'Nie udało się połączyć z komputerem ({attempts} {attemptWord}{elapsed}).', 'connection.error.elapsed': ', {seconds} s', 'connection.error.tip': 'Sprawdź kod na ekranie komputera i upewnij się, że oba urządzenia mają internet. Szczegóły znajdziesz pod przyciskiem „Sprawdź połączenie”.', 'connection.attempt.one': 'próba', 'connection.attempt.many': 'próby',
    'connection.reject.disconnected': 'Odłączono przez administratora.', 'connection.reject.version': 'Niezgodna wersja gry — odśwież stronę na telefonie.', 'connection.reject.token': 'Ten link kontrolera jest nieaktualny. Zeskanuj aktualny kod QR z ekranu.', 'connection.reject.locked': 'Pokój jest zamknięty. Poproś administratora o otwarcie wejścia.', 'connection.reject.full': 'Wszystkie 4 miejsca są zajęte.',
    'host.defaultNick': 'Telefon {n}', 'host.slotName': 'GRACZ {n}', 'host.error.signalLost': 'Utracono łączność z serwerem sygnalizacji.', 'host.error.registerTimeout': 'Serwer sygnalizacji nie odpowiedział podczas rejestracji pokoju.', 'host.error.browserUnsupported': 'Ta przeglądarka nie obsługuje WebRTC — tryb „telefon jako pad” nie zadziała.', 'host.error.codeBusy': 'Kod {code} jest chwilowo zajęty — próbuję ponownie.', 'host.error.codeTaken': 'Kod pokoju był zajęty na serwerze.', 'host.note.codeRefreshed': 'Kod pokoju został odświeżony — zeskanuj nowy kod QR na telefonach.', 'host.error.signalOffline': 'Brak łączności z serwerem sygnalizacji.', 'host.error.server': 'Błąd serwera sygnalizacji{type}.', 'host.error.signalLostRelay': 'Serwer sygnalizacji nie odpowiada — bezpośrednie łączenie z telefonami jest niedostępne, ale działa awaryjny przekaźnik (Wi‑Fi ↔ LTE).', 'host.error.signalLostNoRelay': 'Serwer sygnalizacji nie odpowiada — telefony nie zobaczą pokoju, dopóki połączenie nie wróci. Łączę awaryjny przekaźnik i ponawiam próbę automatycznie.', 'host.error.roomDisappeared': 'Pokój zniknął z serwera sygnalizacji — odświeżam rejestrację.', 'host.error.relayLost': 'Awaryjny przekaźnik rozłączony — łączę ponownie…',
    'gallery.noMatches': 'Brak klipów pasujących do tego filtra.', 'gallery.deleteError': 'Nie udało się usunąć tego klipu.',
    'replay.aria': 'Powtórka wideo z rozgrywki', 'replay.playError': 'Naciśnij odtwarzanie na dużym ekranie albo pobierz klip, jeśli przeglądarka blokuje odtwarzacz.', 'replay.formatError': 'Nie można odtworzyć tego formatu w tej przeglądarce. Możesz pobrać klip.', 'replay.startError': 'Użyj przycisku odtwarzania na dużym ekranie.', 'replay.captured': 'RZECZYWISTE NAGRANIE · BEZ DŹWIĘKU', 'replay.recordingDisabled': 'Nagrywanie Momentów wyłączone w ustawieniach TV.', 'replay.unsupported': 'Ta przeglądarka nie obsługuje nagrywania Momentów. Spróbuj aktualnego Chrome, Edge lub Safari na dużym ekranie.', 'replay.setupFailed': 'Nie udało się przygotować nagrywania. Gra działa dalej.', 'replay.pauseFailed': 'Przeglądarka przerwała nagrywanie podczas pauzy.', 'replay.frameFailed': 'Nagrywanie zostało przerwane (kodek, zasoby lub niedostępny obraz gry).', 'replay.memoryLimit': 'Osiągnięto limit pamięci Momentów. Zachowano wcześniej ukończone klipy.', 'replay.codecFailed': 'Kodek przerwał nagrywanie. Zachowano wcześniej ukończone klipy.', 'moments.notice.preparing': 'Przygotowujemy Twoje powtórki…', 'moments.notice.partial': 'Nie wszystkie akcje mają nagranie — brak klatki lub klip poza zachowanym buforem.', 'moments.notice.failed': 'Nie udało się zapisać powtórek. Wyniki i opisy akcji pozostają dostępne.', 'replay.action': 'Akcja:', 'replay.pause': 'Pauza', 'replay.play': 'Odtwórz', 'replay.fromStart': 'Od początku', 'replay.speed': 'Tempo', 'replay.download': 'Pobierz klip', 'replay.moment': 'Moment', 'replay.actionNumber': 'Akcja',
    'diagnostics.title': 'SPRAWDŹ POŁĄCZENIE', 'diagnostics.checking': 'Sprawdzam…', 'diagnostics.running': 'sprawdzam…', 'diagnostics.checkingAgain': 'SPRAWDZAM…', 'diagnostics.retry': 'SPRAWDŹ JESZCZE RAZ',
    'diagnostics.summary.directBlocked': 'Łączenie bezpośrednie jest zablokowane, ALE awaryjny przekaźnik łączy urządzenia — gra powinna działać.', 'diagnostics.summary.fail': 'Coś blokuje połączenie — szczegóły niżej.', 'diagnostics.summary.relayNetworks': 'Różne sieci (Wi‑Fi ↔ LTE) połączą się przez awaryjny przekaźnik — bez konfiguracji.', 'diagnostics.summary.warn': 'Połączenie zadziała, ale najlepiej w tej samej sieci Wi‑Fi.', 'diagnostics.summary.ok': 'Wszystkie ogniwa łączności działają.',
    'diagnostics.browser': 'Przeglądarka', 'diagnostics.browser.running': 'sprawdzam…', 'diagnostics.browser.unsupported': 'Ta przeglądarka nie obsługuje WebRTC.', 'diagnostics.browser.hint': 'Otwórz grę w aktualnej wersji Chrome, Safari, Edge albo Firefoksa.', 'diagnostics.browser.secure': 'WebRTC działa, strona jest bezpieczna (HTTPS).', 'diagnostics.browser.insecure': 'WebRTC działa, ale strona nie jest otwarta przez HTTPS — niektóre funkcje mogą być zablokowane.',
    'diagnostics.signalHttp': 'Serwer sygnalizacji (HTTP)', 'diagnostics.signalHttp.running': 'pytam o identyfikator…', 'diagnostics.signalHttp.response': 'Odpowiedź w {time} — {host}:{port}.', 'diagnostics.signalHttp.slow': 'Serwer odpowiada wolno — łączenie może potrwać dłużej; gra ponawia próby automatycznie.', 'diagnostics.signalHttp.fail': 'Brak odpowiedzi z {host}:{port} ({error}).', 'diagnostics.signalHttp.hint': 'Serwer sygnalizacji jest niedostępny — bez niego komputer i telefon nie mogą się odnaleźć. Spróbuj za chwilę, sprawdź filtr sieci/VPN albo wskaż własny serwer parametrem ?srv=host:port.',
    'diagnostics.signalWs': 'Serwer sygnalizacji (WebSocket)', 'diagnostics.signalWs.running': 'otwieram połączenie…', 'diagnostics.signalWs.skipped': 'Pominięte — serwer nie odpowiada po HTTP.', 'diagnostics.signalWs.open': 'Połączenie otwarte w {time}.', 'diagnostics.signalWs.slow': 'To ten etap zwykle odpowiada za przekroczony czas. Gra czeka na serwer do 25 s i ponawia próbę.', 'diagnostics.signalWs.fail': 'Nie udało się otworzyć połączenia ({error}).', 'diagnostics.signalWs.hint': 'Sieć blokuje połączenia WebSocket do serwera sygnalizacji (często firmowe Wi‑Fi, VPN lub filtr rodzicielski). Spróbuj innej sieci, np. hotspotu z telefonu.', 'diagnostics.probe.timeout': 'brak odpowiedzi', 'diagnostics.probe.socket': 'nie można otworzyć połączenia', 'diagnostics.probe.rejected': 'serwer odrzucił połączenie WebSocket',
    'diagnostics.stun': 'STUN (adres publiczny)', 'diagnostics.stun.running': 'zbieram kandydatów…', 'diagnostics.stun.public': 'Publiczny adres wykryty w {time}.', 'diagnostics.stun.missing': 'Brak odpowiedzi serwerów STUN — wykryto tylko adresy lokalne.', 'diagnostics.stun.missingHint': 'Połączenie zadziała, gdy komputer i telefon są w tej samej sieci Wi‑Fi. Dla różnych sieci potrzebny jest działający STUN/TURN. W sieci firmowej lub przez VPN spróbuj hotspotu z telefonu.', 'diagnostics.stun.mdns': 'Wykryto lokalne kandydaty mDNS (.local) — przeglądarka ukrywa adresy dla prywatności.', 'diagnostics.stun.mdnsHint': 'To normalne w Chrome i Firefoxie. Połączenie w tej samej sieci Wi‑Fi powinno działać mimo tego komunikatu.', 'diagnostics.stun.fail': 'Nie udało się zebrać żadnych kandydatów sieciowych{details}.', 'diagnostics.stun.localError': ' / lokalnie: {error}', 'diagnostics.stun.failHint': 'Wygląda na to, że przeglądarka całkowicie zablokowała WebRTC. Sprawdź VPN, zaporę, tryb prywatny, rozszerzenia blokujące i dostęp do internetu.',
    'diagnostics.turn': 'TURN (przekaźnik)', 'diagnostics.turn.running': 'pytam przekaźnik o miejsce…', 'diagnostics.turn.readyDedicated': 'Skonfigurowany przekaźnik TURN gotowy w {time}.', 'diagnostics.turn.readyShared': 'Współdzielony przekaźnik TURN gotowy w {time}.', 'diagnostics.turn.failDedicated': 'Skonfigurowany przekaźnik TURN nie odpowiedział{error}.', 'diagnostics.turn.failShared': 'Współdzielony darmowy przekaźnik TURN nie odpowiedział{error}.', 'diagnostics.turn.hintDedicated': 'Sprawdź adres, port, transport oraz dane logowania TURN. Do połączeń między Wi‑Fi i LTE serwer musi zwrócić kandydata relay.', 'diagnostics.turn.hintShared': 'Gra może nadal połączyć różne sieci przez awaryjny przekaźnik poniżej. Własny TURN zwykle łączy szybciej (szczegóły w README).',
    'diagnostics.relay': 'Awaryjny przekaźnik (Wi‑Fi ↔ LTE)', 'diagnostics.relay.running': 'testuję publiczny przekaźnik wiadomości…', 'diagnostics.relay.ready': 'Przekaźnik gotowy w {time} ({host}) — urządzenia w RÓŻNYCH sieciach też się połączą, nawet gdy WebRTC/TURN nie działa.', 'diagnostics.relay.readyHint': 'To awaryjna ścieżka: gra korzysta z niej tylko, gdy łączenie bezpośrednie nie działa. Jest o kilkadziesiąt ms wolniejsza od WebRTC.', 'diagnostics.relay.fail': 'Żaden z publicznych przekaźników nie odpowiedział (albo sieć je blokuje).', 'diagnostics.relay.failHint': 'Bez przekaźnika i TURN łączenie między różnymi sieciami może nie zadziałać. Dodaj własny TURN parametrami ?turn=turn:host:3478 i opcjonalnie ?turnUser= oraz ?turnPass= albo skonfiguruj VITE_TURN_* podczas wdrożenia.'
  },
  en: {
    'common.close': 'Close', 'common.cancel': 'Cancel', 'common.confirm': 'Confirm', 'common.back': 'Back',
    'common.language': 'Interface language', 'common.languageDetail': 'Polski and English — applies to TV and controllers.',
    'common.gallery': 'Moments Gallery', 'common.save': 'Save to Moments Gallery', 'common.saved': 'Saved to gallery', 'qr.loading': 'Generating code…', 'qr.alt': 'QR code to connect a phone',
    'notifications.aria': 'Notifications', 'notifications.close': 'Close notification', 'notifications.playerJoined': '{name} joined the crew', 'notifications.playerConnected': 'Controller {n} is connected. Welcome!', 'notifications.suggestsGame': '{name} suggested a game', 'notifications.ready': '{name} is ready', 'notifications.readyDetail': 'Ready to play!', 'notifications.playerLeft': '{name} left the room', 'notifications.returnDetail': 'Their spot is waiting if they reconnect.', 'notifications.newAdmin': 'New room admin', 'notifications.roomLocked': 'The room is now closed to new players', 'notifications.roomOpen': 'The room is open to new players', 'notifications.suggestionsOn': 'Game suggestions enabled', 'notifications.suggestionsOff': 'Game suggestions paused',
    'library.aria': 'JoyPad library', 'library.system': 'Console system', 'library.roomLocked': 'Room locked', 'library.roomReady': 'Room ready', 'library.roomConnecting': 'Connecting to room',
    'library.musicOff': 'Turn menu music off', 'library.musicOn': 'Turn menu music on', 'library.settings': 'System settings', 'library.room': 'Room', 'library.addPlayer': 'Add player',
    'library.heading': 'YOUR LIBRARY', 'library.launch': 'Launch game', 'library.playAgain': 'Play again', 'library.lastSettings': 'Last settings · new round',
    'library.session': 'Your session', 'library.sharedScreen': 'SHARED SCREEN', 'library.chooseAndPrepare': 'Choose a game and prepare the round.', 'library.roomCode': 'ROOM CODE', 'library.openPad': 'Open controller',
    'library.admin': 'Admin', 'library.connected': 'Connected', 'library.waitingPlayer': 'Waiting for player', 'library.crewVotes': 'CREW PICKS', 'library.connectionIssue': 'Connection issue · details',
    'library.invite': "What are we playing?", 'library.availableGames': 'Available games', 'library.upcoming': 'Coming soon', 'library.choose': 'Choose', 'library.start': 'Start', 'library.remoteHint': 'Remote · keyboard · gamepad',
    'library.whatsNew': "What's new?", 'library.howToStart': 'How to start', 'library.version': 'JOYPAD OS · 1.7.0', 'library.musicDisable': 'Turn off', 'library.musicEnable': 'Turn on', 'library.libraryMusic': 'library music',
    'library.soonTitle': 'Coming to the library', 'library.soonNote': 'New worlds will arrive when they are ready — no countdowns or promised dates.', 'library.inDevelopment': 'Coming soon',
    'library.helpTitle': 'Sit down. Connect. Play.', 'library.helpScreenTitle': 'Big screen', 'library.helpScreen': 'Open JoyPad on a computer or TV. You can play with a keyboard.',
    'library.helpPhoneTitle': 'Your phone, your controller', 'library.helpPhone': 'Scan the QR code. The first connected phone controls the menu; other players join without an account.',
    'library.helpGameTitle': 'Choose your world', 'library.helpGame': 'Use the arrows to choose a game and Enter to open it. Your phone becomes a controller; a gamepad can navigate the library.',
    'library.padCheck': 'Test controller · movement and action', 'library.chooseWorld': 'What are we playing?',
    'setup.back': 'JOYPAD / GAMES', 'setup.prepare': 'GAME SETUP', 'setup.nextRound': 'YOUR NEXT ROUND', 'setup.settingsCrewStart': 'Settings, crew, start.', 'setup.crew': 'Your crew',
    'setup.keyboard': 'Keyboard', 'setup.freeSlot': 'Open slot', 'setup.ready': 'READY ✓', 'setup.connected': 'CONNECTED', 'setup.player': 'PLAYER {n}', 'setup.slot': 'SLOT {n}',
    'setup.nextStep': 'NEXT STEP', 'setup.invite': 'Invite controllers', 'setup.start': 'Start game', 'setup.local': 'Play locally · no phone needed', 'setup.padCount': '{n} controllers · continue to round',
    'setup.rules': 'HOW TO PLAY', 'setup.howToPlay': 'How to play', 'setup.goal': 'Goal:', 'setup.phone': 'Controller:', 'setup.mainOption': 'Primary option', 'setup.secondOption': 'Secondary option', 'setup.keyboardHelp': 'WASD / arrows + Q / Enter · P / Esc = pause',
    'game.statusLoading': 'LOADING ARENA…', 'game.matchTournament': 'TOURNAMENT {n}/3', 'game.shared': 'SHARED', 'game.split': 'SPLIT SCREEN', 'game.quality': 'QUALITY', 'game.actionBonus': 'TRACK BONUS',
    'game.ready': 'GET READY', 'game.start': 'START', 'game.loading': 'Loading arena…', 'game.soundOn': 'Turn sound on', 'game.mute': 'Mute', 'game.pads': 'Controllers and room code', 'game.pause': 'Pause (P)', 'game.endRound': 'End round', 'game.back': 'Back to JoyPad',
    'results.roundEnd': 'ROUND COMPLETE', 'results.library': 'Library', 'results.sharedWin': 'TEAM VICTORY', 'results.yourMoment': 'THIS MOMENT IS YOURS', 'results.newStory': 'EVERY ROUND TELLS A NEW STORY',
    'results.teamWins': 'TEAM WINS', 'results.victory': 'VICTORY', 'results.summary': 'ROUND SUMMARY', 'results.team': 'Whole team', 'results.goalReached': 'Shared goal reached', 'results.localRecord': 'LOCAL RECORD',
    'results.lastMove': 'AFTER THE LAST MOVE', 'results.roundScores': 'Round results.', 'results.players': 'PLAYERS', 'results.rank': 'PLAYER / RANK', 'results.stats': 'Your stats · every score matters',
    'results.proposals': 'Crew picks', 'results.choose': 'Choose: {title}', 'results.approval': 'Confirming opens setup; it does not start the round.', 'results.wantsRematch': '{ready}/{total} want a rematch', 'results.rematchPrompt': 'Join from your phones',
    'results.rematch': 'Rematch', 'results.sameSettings': 'Same settings. A new chance.', 'results.changeGame': 'Change game', 'results.backLibrary': 'Back to library', 'results.changeSettings': 'Change settings', 'results.battleMenu': 'Match menu', 'results.nextWorld': 'Choose the next world',
    'moments.aria': 'Moments — best plays from the round', 'moments.highlights': 'MOMENTS / HIGHLIGHTS', 'moments.videoHighlights': 'VIDEO HIGHLIGHTS',
    'moments.description': 'Automatic highlights from the round. Watch them now or save selected clips locally in your Moments Gallery.', 'moments.watch': 'WATCH', 'moments.eventDetails': 'EVENT DETAILS · NO VIDEO',
    'moments.saved': 'SAVED TO GALLERY', 'moments.saving': 'SAVING…', 'moments.saveGallery': 'SAVE TO MOMENTS GALLERY', 'moments.empty': 'No standout plays were captured this round. The next round is a new story.',
    'moments.roundTime': 'round time', 'moments.noVideo': 'No video was available for this confirmed game event.', 'moments.clipInfo': 'The clip includes a short window before and after the action.',
    'moments.saveError': 'Could not save the clip. Browser storage may be unavailable.',
    'gallery.local': 'Your local collection', 'gallery.localInfo': 'Clips stay on this device. Nothing is uploaded to the internet.',
    'gallery.empty': 'Your gallery is empty. Save a great play after a round to keep it here.', 'gallery.unavailable': 'The gallery is not available in this browser.', 'gallery.play': 'Play', 'gallery.download': 'Download', 'gallery.share': 'Share', 'gallery.delete': 'Delete', 'gallery.deleteConfirm': 'Delete this clip from this device?',
    'gallery.filter': 'Filter games', 'gallery.allGames': 'All games', 'gallery.sort': 'Sort by', 'gallery.newest': 'Newest first', 'gallery.oldest': 'Oldest first', 'gallery.storage': 'Storage used', 'gallery.items': 'clips', 'gallery.close': 'Close', 'gallery.shareUnavailable': 'Sharing is not supported. You can download the clip instead.',
    'settings.system': 'YOUR SYSTEM', 'settings.intro': 'Small details.<br />Your experience.', 'settings.sound': 'System sound', 'settings.soundDetail': 'A subtle sound. A clear response.', 'settings.soundAria': 'System sounds',
    'settings.soundOn': 'Sound on', 'settings.silence': 'Silent', 'settings.bigScreenOnly': 'Big screen only', 'settings.motion': 'Motion and transitions', 'settings.motionDetail': 'Calm pacing without losing responsiveness.', 'settings.motionAria': 'Interface motion', 'settings.motionSystem': 'System setting', 'settings.motionDevice': 'Follow device preference', 'settings.motionReduced': 'Reduced', 'settings.noTransitions': 'Limit transition animations',
    'settings.previews': 'Game previews', 'settings.previewDetail': 'Full HD recordings, muted, without running a game in the background.', 'settings.previewAuto': 'Automatic on big screens', 'settings.previewManual': 'Only when play is pressed', 'settings.previewRules': 'Phones, data saver and reduced motion: manual start.',
    'settings.moments': 'Moments · video replays', 'settings.momentsDetail': 'Game capture up to 720p / 24 FPS. No audio, camera or microphone. Clips stay on this device.', 'settings.recordOn': 'Save standout plays', 'settings.recordOff': 'Recording off', 'settings.recordRules': 'From the next round · disable on slower devices. Clips clear when you leave the game; you can download them.',
    'settings.controllerProfile': 'CONTROLLER PROFILE', 'settings.feel': 'Feel the response', 'settings.hapticsDetail': 'Pulse length and rhythm, not motor strength.', 'settings.haptics': 'Haptics', 'settings.hapticsOff': 'Off', 'settings.subtle': 'Subtle', 'settings.full': 'Strong',
    'settings.hand': 'Fit your hands', 'settings.handDetail': 'Arcade action-button side. Tanks have a separate layout.', 'settings.actionButton': 'Action button', 'settings.left': 'Left', 'settings.right': 'Right',
    'settings.controlSize': 'Control size', 'settings.height': 'Thumb reach', 'settings.compact': 'Compact', 'settings.large': 'Large', 'settings.lower': 'Lower', 'settings.higher': 'Higher', 'settings.saveAuto': 'Saved automatically on this device', 'settings.saveLocal': 'If the browser allows local storage',
    'settings.phoneFeatures': 'PHONE FEATURES', 'settings.preventSleep': 'Keep screen awake', 'settings.fullscreenLandscape': 'Fullscreen and landscape', 'settings.tilt': 'Tilt controls', 'settings.optionalMode': 'Optional mode:', 'settings.privacy': 'The controller does not need your camera, microphone, location or notifications.',
    'room.screen': 'BIG SCREEN', 'room.fullscreen': 'Fullscreen', 'room.fullscreenOn': 'Picture fills the TV', 'room.fullscreenOff': 'Browser window', 'room.sectionSwitches': 'ROOM', 'room.intro': 'Your crew, your rules. Changes apply to the TV and every phone.', 'room.lock': 'Lock the room', 'room.locked': 'New phones cannot join', 'room.open': 'Invites are open', 'room.voice': 'Crew votes', 'room.voteInfo': 'Suggest games in the library and after a round',
    'room.dim': 'Big-screen break', 'room.dimGame': 'Available outside an active round', 'room.dimInfo': 'Hide the library while keeping connections', 'room.crew': 'CREW / {count} OF 4', 'room.admin': 'Admin', 'room.pad': 'Controller {n}',
    'room.noPlayers': 'Just the big screen for now. Invite the first phone.', 'room.transferAria': 'Transfer admin to: {name}', 'room.disconnectAria': 'Disconnect: {name}', 'room.kickTitle': 'Disconnect {name}?', 'room.transferTitle': 'Transfer control to {name}?',
    'room.kickInfo': 'This phone will lose its connection. To prevent it from joining again, lock the room.', 'room.transferInfo': 'This player will control the menu and room. The big screen always keeps control.', 'room.confirm': 'Confirm', 'room.cancel': 'Cancel',
    'pad.room': 'ROOM', 'pad.reminder': 'The crew is waiting. Confirm when you are ready.', 'pad.paused': 'PAUSED · TAKE A BREATHER', 'pad.ready': 'READY · {count}',
    'snake.direction': 'Choose a direction.', 'snake.starting': 'Get ready to start.', 'snake.instruction': 'Tap an arrow to change direction. Do not turn back into yourself.', 'snake.dpad': 'Snake direction controls', 'snake.sprint': 'SPRINT', 'snake.hold': 'HOLD', 'snake.settingsInfo': 'Snake Vortex uses four directional buttons. A tap is enough — no need to steer a stick.', 'snake.beta': 'BETA', 'snake.newGame': 'NEW GAME', 'snake.points': '{score} pts', 'snake.backToLibrary': 'Return to the library?', 'snake.pause': 'Pause', 'snake.settings': 'Controller settings', 'snake.fullscreen': 'Fullscreen', 'snake.disconnect': 'Disconnect phone', 'snake.paused': 'PAUSED',
    'joylab.title': 'CONTROLLER LAB', 'joylab.playroom': 'PLAYROOM', 'joylab.skip': 'BACK / SKIP →', 'joylab.intro': 'Explore the controller’s responses. Touch always works; sensors and vibration depend on your device. You can skip the test at any time.', 'joylab.enableSensors': 'ENABLE SENSORS (accelerometer + gyroscope)', 'joylab.shake': 'SHAKE = RATTLE', 'joylab.tilt': 'TILT = GRAVITY', 'joylab.touchZones': 'TOUCH THE ZONES', 'joylab.simulateShake': 'SIMULATE SHAKE', 'joylab.zonesInfo': 'EACH ZONE HAS A DIFFERENT VIBRATION · TRY ALL 8', 'joylab.meter.gravityX': 'GRAV-X', 'joylab.meter.gravityY': 'GRAV-Y', 'joylab.meter.shake': 'SHAKE', 'joylab.meter.gyro': 'GYRO', 'joylab.zone.click': 'CLICK', 'joylab.zone.double': 'DOUBLE', 'joylab.zone.buzz': 'BUZZ', 'joylab.zone.heart': 'HEART', 'joylab.zone.flutter': 'FLUTTER', 'joylab.zone.burst': 'BURST', 'joylab.zone.wave': 'WAVE', 'joylab.zone.drum': 'DRUM',
    'pad.quick.title': 'Test your controller', 'pad.quick.instruction': 'Move the stick and press the action button. You will see the response on the TV.', 'pad.quick.skip': 'Done / skip', 'pad.quick.explore': 'Sensors and haptics', 'pad.quick.moveCaption': 'MOVE THE STICK', 'pad.quick.action': 'ACTION', 'pad.quick.actionAria': 'Test action button', 'pad.quick.dialog': 'Controller lab', 'pad.quick.headline': 'One move. That is all it takes.', 'pad.quick.tvInstruction': 'Move the stick on your phone, then press the action button. The test needs no sensors or vibration.', 'pad.quick.noPhones': 'Connect a phone to start the test. You can also go back and play with the keyboard.', 'pad.quick.move': 'Movement', 'pad.quick.moveVerified': 'checked', 'pad.quick.movePrompt': '— move the stick', 'pad.quick.actionVerified': 'checked', 'pad.quick.actionPrompt': '— press the button', 'pad.quick.exploreSensors': 'Explore sensors and haptics', 'pad.quick.optional': 'The test is optional. Return to the library whenever you like.', 'pad.quick.backLibrary': 'To library', 'pad.quick.testedAction': 'ACTION',
    'controller.title': 'Your controller', 'controller.disconnect': 'Disconnect phone', 'controller.backLibrary': 'Return to the library?', 'controller.pauseResume': 'PAUSE / RESUME', 'controller.allGames': 'ALL GAMES', 'controller.confirmExit': 'End the round?', 'controller.nickTitle': 'YOUR NICKNAME', 'controller.nickDetail': 'Shown in the lobby and every game', 'controller.editNick': 'EDIT', 'controller.nickname': 'Player nickname', 'controller.saveNick': 'SAVE',
    'controller.exitInfo': 'Everyone will return to the library. Phone connections will stay active.', 'controller.yesLibrary': 'Yes, return to library', 'controller.stay': 'Stay in the game',
    'pad.connect': 'CONNECT', 'pad.connecting': 'CONNECTING…', 'pad.phoneController': 'PHONE CONTROLLER', 'pad.sharedScreen': 'One shared screen. Your phone. One game system.', 'pad.roomCode': 'CODE FROM THE BIG SCREEN', 'pad.yourNick': 'YOUR NICKNAME', 'pad.joined': 'JOINED THE ROOM', 'pad.youArePlayer': 'YOU ARE PLAYER',
    'pad.connectAgain': 'Reconnecting. Controls are safely stopped.', 'pad.connectingPad': 'Connecting your controller…', 'pad.rotate': 'Rotate your phone to landscape and tap to enter fullscreen',
    'pad.levels': 'VOLUME LEVEL', 'pad.rumble': 'SHAKE', 'pad.gyro': 'GYRO', 'pad.playroom': 'PLAYROOM', 'pad.skip': 'BACK / SKIP →', 'pad.sensorIntro': 'Try your controller’s responses. Touch always works; sensors and vibration depend on your device. You can skip at any time.',
    'pad.enableSensors': 'ENABLE SENSORS (accelerometer + gyroscope)', 'pad.shake': 'SHAKE = RATTLE', 'pad.simulateShake': 'SIMULATE SHAKE', 'pad.allZones': 'EACH ZONE HAS ITS OWN VIBRATION · TRY ALL 8',
    'pad.nicknameExample': 'e.g. Alex', 'pad.connectionDetails': 'Connection details', 'pad.elapsed': 'Time:', 'pad.server': 'Server:', 'pad.stop': 'CANCEL', 'pad.details': 'Details:',
    'pad.instructions.open': 'Open JoyPad on a computer or TV.', 'pad.instructions.scan': 'Scan the QR code on screen or enter the 5-character code here.', 'pad.instructions.admin': 'The first phone becomes the admin and chooses the game. Other phones get their own controllers.', 'pad.instructions.connection': 'The connection uses the internet, then links devices directly. If a direct route fails (for example, when a phone is on LTE), the game automatically uses a fallback relay — Wi‑Fi and LTE networks can still play together.', 'pad.openHere': '← Open JoyPad on this device',
    'pad.controlSettings': 'Control settings', 'pad.fullscreen': 'Fullscreen', 'pad.pauseTitle': 'Pause', 'pad.returnTitle': 'Back to JoyPad', 'pad.disconnectTitle': 'Disconnect phone', 'pad.pauseOverlay': 'PAUSED', 'pad.respawn': 'RESPAWNING IN {seconds}s', 'pad.destroyed': 'DESTROYED', 'pad.noTankLead': 'The battle is underway, and your slot', 'pad.noTankTail': 'is not in it. You will join automatically in the next round.',
    'pad.steering': 'Controls', 'pad.move': 'MOVE', 'pad.front': 'FORWARD', 'pad.rear': 'REVERSE', 'pad.driveDirection': 'DRIVE • PUSH TO MOVE', 'pad.driveForward': 'DRIVE • UP = FORWARD', 'pad.directionMode': 'DIRECTION', 'pad.tankMode': 'TANK', 'pad.turret': 'TURRET', 'pad.aimAutoFire': 'AIM • FULL TILT TO FIRE', 'pad.aimTurret': 'AIM THE TURRET', 'pad.fire': 'FIRE', 'pad.holdBurst': 'HOLD = BURST',
    'pad.layoutTitle': 'CONTROLLER LAYOUT', 'pad.layoutMinimal': 'SIMPLE', 'pad.layoutMinimalDesc': '1 stick + 1 action', 'pad.layoutTwin': 'TWIN STICK', 'pad.layoutTwinDesc': 'drive + independent aiming', 'pad.drive': 'DRIVE', 'pad.directionDesc': 'Move where you push the stick', 'pad.tankDesc': 'Up = forward, sides = turn', 'pad.autoFire': 'Auto-fire while aiming', 'pad.autoFireDesc': 'In twin-stick mode, push the aiming stick to the edge (red ring) to fire automatically.', 'pad.swapSides': 'Swap sides', 'pad.swapDesc': 'Drive on the right, aiming and fire on the left (left-handed layout).', 'pad.noTankHeading': 'You will join the next round',
    'device.wake.off': 'off', 'device.wake.waiting': 'checking…', 'device.wake.ready': 'active', 'device.wake.unsupported': 'not supported', 'device.wake.blocked': 'blocked by the system',
    'device.tilt.off': 'off', 'device.tilt.requesting': 'waiting for permission…', 'device.tilt.ready': 'active', 'device.tilt.unsupported': 'sensor/API unavailable', 'device.tilt.denied': 'permission denied', 'device.fullscreen.active': 'active', 'device.fullscreen.unsupported': 'not supported', 'device.fullscreen.blocked': 'tap the button again', 'device.fullscreen.off': 'available after tapping', 'device.test': 'TEST',
    'haptics.status.ready': 'Vibration ready', 'haptics.status.readyDetail': 'The API accepted the test; silent mode, Do Not Disturb or system settings may still mute the pulse.', 'haptics.status.tap': 'Tap to unlock', 'haptics.status.tapDetail': 'The browser does not show a permission prompt. The first tap unlocks the API.', 'haptics.status.unsupported': 'No vibration', 'haptics.status.unsupportedDetail': 'This browser or device does not support the Vibration API (for example, iOS Safari).', 'haptics.status.blocked': 'Vibration blocked', 'haptics.status.blockedDetail': 'System settings, silent mode or missing activation blocked the pulse. Tap TEST again.', 'haptics.status.off': 'Vibration off', 'haptics.status.offDetail': 'Choose subtle or strong in settings to test vibration.',
    'remote.adminNav': 'ADMIN REMOTE', 'remote.up': 'Up', 'remote.left': 'Left', 'remote.select': 'Select', 'remote.right': 'Right', 'remote.down': 'Down', 'remote.back': 'BACK', 'remote.games': 'GAMES', 'remote.onlyAdmin': 'Only the admin can control the menu.', 'remote.arrowsHelp': 'Stick: navigate · OK: confirm · X: fullscreen · Y: QR code', 'remote.x': 'Fullscreen', 'remote.y': 'QR code', 'remote.controllerMode': 'CONTROLLER MODE', 'remote.profile': 'My profile', 'remote.room': 'Room', 'remote.phoneSettings': 'Phone settings', 'remote.lobby': 'LIBRARY', 'remote.results': 'RESULTS', 'remote.prep': 'SETUP', 'remote.roundHint': 'Arrows: Moments and actions. A: select.', 'remote.selectHint': 'Arrows to choose. A to confirm.', 'remote.rotateHint': 'Rotate to portrait to use the remote', 'remote.playerPass': 'Your pad. Your style.', 'remote.crewStarting': 'The crew is about to start.', 'remote.customizePass': 'Customize Player Pass', 'remote.rematchIntent': 'I want a rematch', 'remote.readyIntent': 'I am ready', 'remote.readyIntentDone': 'Ready ✓', 'remote.rematchIntentDone': 'Rematch wanted ✓', 'remote.rematchCount': 'want a rematch', 'remote.readyCount': 'ready', 'remote.hostStarts': 'The host starts the round', 'remote.remind': 'Remind the crew', 'remote.reminded': 'Reminder sent', 'remote.win': 'Victory!', 'remote.roundOver': 'Round complete', 'remote.adminOver': 'Choose a rematch or return to the library.', 'remote.guestOver': 'The admin decides what happens next.', 'remote.adminSettings': 'Use the controls to set up and start the round with OK.', 'remote.guestSettings': 'The admin is setting up the game. Wait for the start.', 'remote.action.rematch': 'REMATCH', 'remote.action.battle': 'BATTLE', 'remote.action.mode': 'CHOOSE MODE', 'remote.action.start': 'START', 'remote.adminRole': 'ADMIN', 'remote.playerRole': 'PLAYER {n}', 'remote.vertical': 'REMOTE MODE / PORTRAIT', 'remote.loungeMode': 'PLAYER LOUNGE', 'remote.selectedGame': 'SELECTED GAME', 'remote.gameMenu': 'GAME MENU', 'remote.navigateAsAdmin': 'Use the remote arrows to choose a game, then press OK.', 'remote.waitForAdmin': 'Wait for the admin to choose a game.', 'remote.navShoulder': 'L / NAVIGATION', 'remote.actionShoulder': 'R / ACTION', 'remote.footerAdmin': 'CONTROL THE BIG SCREEN', 'remote.footerGuest': 'CONNECTED TO THE CREW',
    'arcadePad.nextRound': 'The round is underway. You will join the next one.', 'arcadePad.move': 'MOVE', 'arcadePad.snakeCaption': 'TURN · AVOID WALLS', 'arcadePad.raceCaption': 'STEER', 'arcadePad.orbitCaption': 'FLY · FULL TILT = BOOST', 'arcadePad.characterCaption': 'MOVE YOUR CHARACTER', 'arcadePad.fire': 'FIRE', 'arcadePad.action': 'ACTION', 'arcadePad.turbo': 'TURBO', 'arcadePad.sprint': 'SPRINT', 'arcadePad.raceHint': 'PICKUP / TURBO', 'arcadePad.hold': 'HOLD', 'arcadePad.adminMenu': 'As admin, you can pause the game or return to the library.', 'arcadePad.guestMenu': 'The admin manages the round. You can disconnect this phone.', 'arcadePad.pause': 'PAUSE / RESUME', 'arcadePad.endRound': 'End the round?', 'arcadePad.exitInfo': 'Everyone will return to the library. Phone connections will stay active.', 'arcadePad.yesLibrary': 'Yes, return to library', 'arcadePad.stay': 'Stay in the game', 'arcadePad.menu': 'Menu', 'arcadePad.settings': 'Settings', 'arcadePad.fullscreen': 'Fullscreen', 'arcadePad.roundHint': 'You will join the next round',
    'connection.progress.signal': 'Connecting to the signaling server…', 'connection.progress.signalServer': 'Connecting to the signaling server{server}…', 'connection.progress.signalAttempt': 'Attempt {current}/{total} — connecting to the signaling server{server}…', 'connection.progress.findComputer': 'Looking for a computer with this code…', 'connection.progress.handshake': 'Introducing this phone to the computer…', 'connection.progress.relay': 'Connecting through the fallback relay (internet)…', 'connection.progress.reconnect': 'Reconnecting…', 'connection.progress.retry': '{reason} Retrying in {seconds} s (attempt {current}/{total})…',
    'connection.error.webrtcStart': 'Could not start WebRTC. Check browser connection support and try again.', 'connection.error.linkTimeout': 'The computer did not respond while negotiating a peer-to-peer connection.', 'connection.error.signalTimeout': 'The signaling server did not respond while registering the phone.', 'connection.error.handshake': 'The computer could not assign a place to this phone.', 'connection.error.hostClosed': 'The computer closed the connection.', 'connection.error.peerNotReady': 'The computer is not visible on the server yet.', 'connection.error.peerUnavailable': 'No room was found with this code, either directly or through the fallback relay. The code can change when the computer page refreshes. Scan the QR code again or enter the code shown on screen.', 'connection.error.fallback': 'Could not connect directly (WebRTC) or through the internet fallback relay.', 'connection.error.browserUnsupported': 'This browser does not support WebRTC. Direct connection is unavailable; the fallback relay was also checked.', 'connection.error.signalingRejected': 'The signaling server rejected the connection ({type}).', 'connection.error.signalSsl': 'The signaling server does not support an encrypted connection.', 'connection.error.signalOffline': 'Cannot reach the signaling server.', 'connection.error.signalInterrupted': 'Temporary loss of signaling-server connectivity (the game is still running).', 'connection.error.generic': 'Connection error: {type}.', 'connection.error.lost': 'Connection to the computer was lost — trying to reconnect…', 'connection.error.summary': 'Could not connect to the computer ({attempts} {attemptWord}{elapsed}).', 'connection.error.elapsed': ', {seconds} s', 'connection.error.tip': 'Check the code on the computer screen and make sure both devices have internet access. See details under “Check connection”.', 'connection.attempt.one': 'attempt', 'connection.attempt.many': 'attempts',
    'connection.reject.disconnected': 'Disconnected by the admin.', 'connection.reject.version': 'Game version mismatch — refresh the page on the phone.', 'connection.reject.token': 'This controller link is outdated. Scan the current QR code on screen.', 'connection.reject.locked': 'The room is locked. Ask the admin to open it.', 'connection.reject.full': 'All 4 places are taken.',
    'host.defaultNick': 'Phone {n}', 'host.slotName': 'PLAYER {n}', 'host.error.signalLost': 'Lost connection to the signaling server.', 'host.error.registerTimeout': 'The signaling server did not respond while registering the room.', 'host.error.browserUnsupported': 'This browser does not support WebRTC — phone controllers will not work.', 'host.error.codeBusy': 'Room code {code} is temporarily taken — trying again.', 'host.error.codeTaken': 'The room code was already in use on the server.', 'host.note.codeRefreshed': 'The room code was refreshed — scan the new QR code on each phone.', 'host.error.signalOffline': 'Cannot reach the signaling server.', 'host.error.server': 'Signaling server error{type}.', 'host.error.signalLostRelay': 'The signaling server is not responding — direct phone connections are unavailable, but the fallback relay is active (Wi‑Fi ↔ LTE).', 'host.error.signalLostNoRelay': 'The signaling server is not responding — phones cannot see the room until it reconnects. Connecting the fallback relay and retrying automatically.', 'host.error.roomDisappeared': 'The room disappeared from the signaling server — refreshing registration.', 'host.error.relayLost': 'Fallback relay disconnected — reconnecting…',
    'gallery.noMatches': 'No clips match this filter.', 'gallery.deleteError': 'Could not delete this clip.',
    'replay.aria': 'Gameplay video replay', 'replay.playError': 'Press play on the big screen or download the clip if the browser blocks playback.', 'replay.formatError': 'This browser cannot play this video format. You can download the clip.', 'replay.startError': 'Use the play button on the big screen.', 'replay.captured': 'REAL GAMEPLAY · NO AUDIO', 'replay.recordingDisabled': 'Moments recording is turned off in the TV settings.', 'replay.unsupported': 'This browser does not support Moments recording. Try a recent version of Chrome, Edge or Safari on the big screen.', 'replay.setupFailed': 'Could not prepare recording. The game will continue.', 'replay.pauseFailed': 'The browser stopped recording during the pause.', 'replay.frameFailed': 'Recording stopped (codec, resources or unavailable game image).', 'replay.memoryLimit': 'Moments reached its storage limit. Earlier finished clips were kept.', 'replay.codecFailed': 'The codec stopped recording. Earlier finished clips were kept.', 'moments.notice.preparing': 'Preparing your replays…', 'moments.notice.partial': 'Some actions have no video — a frame was missing or the clip fell outside the saved buffer.', 'moments.notice.failed': 'Could not save the replays. Results and action details are still available.', 'replay.action': 'Action:', 'replay.pause': 'Pause', 'replay.play': 'Play', 'replay.fromStart': 'From start', 'replay.speed': 'Speed', 'replay.download': 'Download clip', 'replay.moment': 'Moment', 'replay.actionNumber': 'Play',
    'diagnostics.title': 'CHECK CONNECTION', 'diagnostics.checking': 'Checking…', 'diagnostics.running': 'checking…', 'diagnostics.checkingAgain': 'CHECKING…', 'diagnostics.retry': 'CHECK AGAIN',
    'diagnostics.summary.directBlocked': 'Direct connections are blocked, BUT the fallback relay connects devices — the game should still work.', 'diagnostics.summary.fail': 'Something is blocking the connection — see details below.', 'diagnostics.summary.relayNetworks': 'Different networks (Wi‑Fi ↔ LTE) can connect through the fallback relay — no setup required.', 'diagnostics.summary.warn': 'The connection should work best when both devices use the same Wi‑Fi network.', 'diagnostics.summary.ok': 'All connection paths are working.',
    'diagnostics.browser': 'Browser', 'diagnostics.browser.running': 'checking…', 'diagnostics.browser.unsupported': 'This browser does not support WebRTC.', 'diagnostics.browser.hint': 'Open the game in the latest version of Chrome, Safari, Edge or Firefox.', 'diagnostics.browser.secure': 'WebRTC works and this page is secure (HTTPS).', 'diagnostics.browser.insecure': 'WebRTC works, but this page is not using HTTPS — some browser features may be blocked.',
    'diagnostics.signalHttp': 'Signaling server (HTTP)', 'diagnostics.signalHttp.running': 'requesting an ID…', 'diagnostics.signalHttp.response': 'Response in {time} — {host}:{port}.', 'diagnostics.signalHttp.slow': 'The server is responding slowly — connecting may take longer; the game will retry automatically.', 'diagnostics.signalHttp.fail': 'No response from {host}:{port} ({error}).', 'diagnostics.signalHttp.hint': 'The signaling server is unavailable — without it, the computer and phone cannot find each other. Try again shortly, check your network filter/VPN, or set a custom server with ?srv=host:port.',
    'diagnostics.signalWs': 'Signaling server (WebSocket)', 'diagnostics.signalWs.running': 'opening connection…', 'diagnostics.signalWs.skipped': 'Skipped — the server did not respond over HTTP.', 'diagnostics.signalWs.open': 'Connection opened in {time}.', 'diagnostics.signalWs.slow': 'This step commonly causes timeouts. The game waits up to 25 seconds for the server and retries.', 'diagnostics.signalWs.fail': 'Could not open the connection ({error}).', 'diagnostics.signalWs.hint': 'The network is blocking WebSocket connections to the signaling server (often corporate Wi‑Fi, a VPN or parental filtering). Try another network, such as a phone hotspot.', 'diagnostics.probe.timeout': 'no response', 'diagnostics.probe.socket': 'could not open the connection', 'diagnostics.probe.rejected': 'the server rejected the WebSocket connection',
    'diagnostics.stun': 'STUN (public address)', 'diagnostics.stun.running': 'collecting candidates…', 'diagnostics.stun.public': 'Public address detected in {time}.', 'diagnostics.stun.missing': 'No response from STUN servers — only local addresses were detected.', 'diagnostics.stun.missingHint': 'The connection should work when the computer and phone are on the same Wi‑Fi network. Different networks require a working STUN/TURN server. On corporate Wi‑Fi or a VPN, try a phone hotspot.', 'diagnostics.stun.mdns': 'Local mDNS (.local) candidates were detected — the browser hides addresses for privacy.', 'diagnostics.stun.mdnsHint': 'This is normal in Chrome and Firefox. Connections on the same Wi‑Fi network should still work.', 'diagnostics.stun.fail': 'Could not collect any network candidates{details}.', 'diagnostics.stun.localError': ' / locally: {error}', 'diagnostics.stun.failHint': 'It looks like the browser has blocked WebRTC entirely. Check your VPN, firewall, private mode, blocking extensions and internet access.',
    'diagnostics.turn': 'TURN (relay)', 'diagnostics.turn.running': 'requesting relay capacity…', 'diagnostics.turn.readyDedicated': 'Configured TURN relay ready in {time}.', 'diagnostics.turn.readyShared': 'Shared TURN relay ready in {time}.', 'diagnostics.turn.failDedicated': 'Configured TURN relay did not respond{error}.', 'diagnostics.turn.failShared': 'Shared free TURN relay did not respond{error}.', 'diagnostics.turn.hintDedicated': 'Check the TURN address, port, transport and credentials. For Wi‑Fi-to-LTE connections, the server must return a relay candidate.', 'diagnostics.turn.hintShared': 'The game may still connect different networks through the fallback relay below. A dedicated TURN server is usually faster (see README).',
    'diagnostics.relay': 'Fallback relay (Wi‑Fi ↔ LTE)', 'diagnostics.relay.running': 'testing public message relays…', 'diagnostics.relay.ready': 'Relay ready in {time} ({host}) — devices on DIFFERENT networks can connect even when WebRTC/TURN fails.', 'diagnostics.relay.readyHint': 'This is a fallback path: the game uses it only when a direct connection fails. It is usually a few dozen milliseconds slower than WebRTC.', 'diagnostics.relay.fail': 'None of the public relays responded (or the network blocks them).', 'diagnostics.relay.failHint': 'Without a relay or TURN, connections across different networks may fail. Add a custom TURN server with ?turn=turn:host:3478 and optional ?turnUser= and ?turnPass= parameters, or configure VITE_TURN_* at deployment.'
  },
};

export function t(language: Language, key: string, values: Record<string, string | number> = {}): string {
  let value = messages[language][key] ?? messages.pl[key] ?? key;
  for (const [name, replacement] of Object.entries(values)) value = value.split(`{${name}}`).join(String(replacement));
  return value;
}

export function useT() {
  const language = useLanguage();
  return { language, t: (key: string, values?: Record<string, string | number>) => t(language, key, values) };
}

export const copy = {
  pl: { language: 'Język interfejsu', languageDetail: 'Polski i English — zmiana obejmuje TV i kontrolery.', gallery: 'Galeria Moments', save: 'Zapisz do Galerii Moments', saved: 'Zapisano w galerii', close: 'Zamknij' },
  en: { language: 'Interface language', languageDetail: 'Polski and English — applies to TV and controllers.', gallery: 'Moments Gallery', save: 'Save to Moments Gallery', saved: 'Saved to gallery', close: 'Close' },
} as const;
